/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#1447FB",
        "primary-hover": "#0E3CE0",
        "primary-light": "#EBF0FF",
        "on-primary": "#ffffff",
        "primary-container": "#EBF0FF",
        "on-primary-container": "#1447FB",
        "inverse-primary": "#1447FB",
        "surface-tint": "#1447FB",
        "surface": "#ffffff",
        "surface-dim": "#f8fafc",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8fafc",
        "surface-container": "#f1f5f9",
        "surface-container-high": "#e2e8f0",
        "surface-container-highest": "#cbd5e1",
        "on-surface": "#1A1A1A",
        "on-surface-variant": "#4B5563",
        "inverse-surface": "#1A1A1A",
        "inverse-on-surface": "#ffffff",
        "outline": "#cbd5e1",
        "outline-variant": "#e2e8f0",
        "secondary": "#1447FB",
        "on-secondary": "#ffffff",
        "secondary-container": "#EBF0FF",
        "on-secondary-container": "#1447FB",
        "tertiary": "#1447FB",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#EBF0FF",
        "primary-fixed-dim": "#D8E0FF",
        "on-primary-fixed": "#0A1460",
        "on-primary-fixed-variant": "#1447FB",
        "background": "#ffffff",
        "on-background": "#1A1A1A",
        "surface-variant": "#f1f5f9",
      },
      borderRadius: {
        DEFAULT: "0.375rem",
        sm: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        xs: "0.5rem",
        sm: "1rem",
        md: "1.5rem",
        lg: "2.5rem",
        xl: "4rem",
        gutter: "24px",
        margin: "32px",
        "container-max": "1280px",
      },
      fontFamily: {
        body: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "mono-code": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-md": [
          "16px",
          { lineHeight: "1.5", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        display: [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "1.3", letterSpacing: "0em", fontWeight: "600" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "mono-code": [
          "14px",
          { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
